# Generated by Django 3.2.5 on 2021-07-27 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210726_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='contentAbout',
            new_name='content_about',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='titleAbout',
            new_name='title_about',
        ),
    ]
